%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 1  

imu_topic: "/imu_apps"  # imu0
# imu_topic: "/imu_raw"  # imu1
# image0_topic: "/lepton0_raw"
# imu_topic: "/imu0"
# imu_topic: "/imu1"
# image0_topic: "/cam1/image_raw"
# image0_topic: "/lepton_r"
# image0_topic: "/lepton_l"
# image0_topic: "/lepton_l_8bit"
image0_topic: "/lepton0_raw"
# image0_topic: "/cir"
# image0_topic: "/cir_norm"
# image0_topic: "/cam3/image_raw"

# image0_topic: "/lepton0_raw_2x"
# image0_topic: "/cam2/image_raw"
# image0_topic: "/cam2_equalized_smoothed/image_raw"
# image0_topic: "/cam2_equalized_smoothed_4x/image_raw"
output_path: "~/output/"

cam0_calib: "cam1_pinhole.yaml"
# cam0_calib: "cam3_pinhole_cir.yaml"
image_width: 160
image_height: 120
# image_width: 640
# image_height: 512


# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   # T_ic:  (cam1 to imu0): 
   # data: [ 0.02737388,  0.9967397,   0.07589886, -0.02749641,
   #       -0.99962523,  0.02731408,  0.00182609, -0.0743362,
   #       -0.00025297, -0.0759204,   0.99711385,  0.32379866,
   #       0.,          0.,          0.,          1.        ]
   # 7/28 data collect
   # data: [-0.00588979,  0.99323074,  0.11600863, -0.22153722,
   #        -0.99969431, -0.00863409,  0.02316772,  0.00612142,
   #         0.02401252, -0.11583671,  0.99297797,  0.24008246,
   #         0.,          0.,          0.,          1.        ]
   # 8/5 data collect
   # data: [-0.01458326, 0.99008587,  0.13970429, -0.1256029,
   #        -0.99902694, -0.02024389, 0.03918361, 0.06281386,
   #         0.0416233,  -0.13899693, 0.98941768, 0.17470608,
   #         0.,         0.,          0.,         1.        ]
   # 8/7 calibration with lotsa motion
   # data: [ 0.0315507,   0.98765565, 0.15343038, -0.08406957,
   #        -0.99794052,  0.02255033, 0.06005172,  0.07384486,
   #         0.05585051, -0.15500906, 0.98633306,  0.13802096,
   #         0.        ,  0.        , 0.        ,  1.        ]
   # vins estimate starting fron 8/7 calib on the calib data -- doesn't do well
   # data: [ 0.03682528,  0.98660308, 0.15892846, -0.08073164,
   #        -0.99805086,  0.02829229, 0.05562406, -0.04077308,
   #         0.05038242, -0.16066706, 0.98572192,  0.11547356,
   #         0.        ,  0.        , 0.        ,  1.        ]
   # data: [-0.00403286,  0.98730015,  0.15881481, -0.10253093,
   #        -0.99994316, -0.00554904,  0.00910453,  0.02816596,
   #         0.00987018, -0.15876907,  0.98726641,  0.10783858,
   #         0.        ,  0.        ,  0.        ,  1.        ]
   # lepton_r 180 fisheye
   # data: [-0.01367001,  0.98324544,  0.18177333, -0.00037093,
   #        -0.99864945, -0.00431244, -0.05177522, -0.00025349,
   #        -0.05012386, -0.1822356 ,  0.98197647,  0.00022901,
   #         0.        ,  0.        ,  0.        ,  1.        ]

   # lepton_l - imu_apps
   # data: [ 0.04159532,  0.98308406,  0.17836916,  0.00124939,
   #        -0.99907938,  0.04280077, -0.00291376, -0.00598234,
   #        -0.01049881, -0.17808375,  0.98395932,  0.00041507,
   #         0.        ,  0.        ,  0.        ,  1.        ]
   # vins estimated from above with calib bag - use this one
   # data: [ 0.0098979 ,  0.97813388,  0.20774059,  0.01641749,
   #        -0.99988406,  0.01208538, -0.00926333,  0.00604817,
   #        -0.01157141, -0.20762481,  0.97814009,  0.03354349,
   #         0.        ,  0.        ,  0.        ,  1.        ]
   # data: [ 0.04663876,  0.98199989,  0.18303288,  0.00104341,
   #        -0.9987356 ,  0.0492827 , -0.00992071, -0.00324167,
   #        -0.01876249, -0.18233877,  0.98305673,  0.00077501,
   #         0.        ,  0.        ,  0.        ,  1.        ]
   # lepton_l - imu_raw
   # data: [-0.99945162,  0.03087246,  0.01197256,  0.1297283 ,
   #        -0.03241936, -0.98592573, -0.16401049,  0.04404902,
   #         0.00674065, -0.16430869,  0.98638594,  0.20001004,
   #         0.        ,  0.        ,  0.        ,  1.        ]
   # vins fusion estimated from above with calib bag - use this one
   # data: [-0.9997769,   0.01918448,  0.00883807,  0.06701474,
   #        -0.02052967, -0.98099628 ,-0.19293739 , 0.03939478,
   #         0.00496871, -0.19307579 , 0.98117127 , 0.09858337,
   #         0.        ,  0.         , 0.         , 1.        ]
   # data: [-0.99884154,  0.03881287,  0.02844524,  0.22956995,
   #        -0.04323519, -0.98336845, -0.1764007 ,  0.10063158,
   #         0.02112553, -0.17742618,  0.98390734,  0.31094834,
   #         0.        ,  0.        ,  0.        ,  1.        ]
   # data: [-0.9997324 ,  0.02004422,  0.01154796,  0.07983052,
   #        -0.02191043, -0.98060634, -0.1947592 ,  0.02490298,
   #         0.0074202 , -0.1949601 ,  0.98078311,  0.1128002 ,
   #         0.        ,  0.        ,  0.        ,  1.        ]

   # lepton57
   # data: [-0.04797276, -0.99828998,  0.03340256, -0.06125335,
   #         0.99883869, -0.04779612,  0.00606723,  0.03785457,
   #        -0.00446034,  0.03365483,  0.99942356,  0.00845617,
   #         0.        ,  0.        ,  0.        ,  1.        ]
   # vins optimized on calib bag
   data: [-0.00792407, -0.99981406,  0.01758022,  0.01083055,
           0.9998778 , -0.00815905, -0.01333494,  0.02143264,
           0.0134759 ,  0.0174724 ,  0.99975653,  0.01212692,
           0.        ,  0.        ,  0.        ,  1.        ]

   # cir imu_raw
   # data: [-0.99999067,  0.00356502,  0.00243826,  0.06116644,
   #        -0.00387736, -0.98969276, -0.14315447,  0.02480758,
   #         0.00190278, -0.14316259,  0.98969735,  0.11390442,
   #         0.        ,  0.        ,  0.        ,  1.        ]
   # cir imu_apps
   # data: [ 0.04095635,  0.98947046,  0.13881922,  0.00216221,
   #        -0.99848882,  0.03543666,  0.04200376,  0.01809037,
   #         0.03664219, -0.14032977,  0.98942655,  0.07441883,
   #         0.        ,  0.        ,  0.        ,  1.        ]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
# min_dist: 30            # min distance between two features 
# min_dist: 20            # min distance between two features 
min_dist: 10            # min distance between two features 
# min_dist: 8            # min distance between two features 
freq: 0                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation.
                        # If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

# Failure detection parameters
max_acceleration: 50.0     # Maximum allowed acceleration (m/s^2)
max_angular_vel: 5.0       # Maximum allowed angular velocity (rad/s)
max_translation: 15.0       # Maximum translation between frames (m)
max_rotation: 30.0         # Maximum rotation between frames (degrees)
min_tracked_features: 10   # Minimum number of tracked features
enable_failure_recovery: 0 # Enable/disable failure recovery

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 5.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
# acc_n: 0.007 #continous
# acc_w: 0.0002 
# gyr_n: 0.0028 #continous
# gyr_w: 4.0e-06
# acc_n: 0.07
# acc_w: 0.002 
# gyr_n: 0.028
# gyr_w: 4.0e-05
# acc_n: 0.7
# acc_w: 0.02 
# gyr_n: 0.28
# gyr_w: 4.0e-04
# acc_n: 0.1
# acc_w: 0.001
# gyr_n: 0.01
# gyr_w: 0.0001

# imu_apps, imu0
# acc_n: 0.05333
# acc_w: 0.00357402
# gyr_n: 0.0002
# gyr_w: 1.565e-06
# 10x or 2x
# acc_n: 0.10666
# acc_w: 0.0357402
# gyr_n: 0.0004
# gyr_w: 1.565e-05
# 10x - use these
# acc_n: 0.5333
# acc_w: 0.0357402
# gyr_n: 0.002
# gyr_w: 1.565e-05
# use these
acc_n: 0.1
acc_w: 0.01
gyr_n: 0.01
gyr_w: 0.001

# imx5 inertial sense
# original params too sensitive (fails on calib bag)
# acc_n: 0.0026
# acc_w: 0.000036
# gyr_n: 0.003
# gyr_w: 1.0e-06
# 10x or 2x
# acc_n: 0.0052
# acc_w: 0.00036
# gyr_n: 0.006
# gyr_w: 1.0e-05
# 10x - use these (100x fails)
# acc_n: 0.026
# acc_w: 0.00036
# gyr_n: 0.03
# gyr_w: 1.0e-05

# acc_n: 1.
# acc_w: 1.
# gyr_n: 1.
# gyr_w: 1.
# acc_n: 1.e-3
# acc_w: 1.e-4
# gyr_n: 1.e-5
# gyr_w: 1.e-6
# acc_n: 0.1
# acc_w: 0.01
# gyr_n: 0.001
# gyr_w: 0.0001

# icm
# acc_n: 0.1          # accelerometer measurement noise standard deviation. 
# gyr_n: 0.05         # gyroscope measurement noise standard deviation.     
# acc_w: 0.0002        # accelerometer bias random work noise standard deviation.  
# gyr_w: 0.000004       # gyroscope bias random work noise standard deviation.   

# lsm
# acc_n: 1.          # accelerometer measurement noise standard deviation. 
# gyr_n: 0.1         # gyroscope measurement noise standard deviation.     
# acc_w: 0.01        # accelerometer bias random work noise standard deviation.  
# gyr_w: 0.001       # gyroscope bias random work noise standard deviation.     

g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0
# td: 0.0                      # online estimate time offset between camera and imu
# td: -0.14309427638297506            # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
# td: -0.01
# td: -0.1440295448279109
# td: -0.14943744155447714
# td: -0.1467966057620003
# td: -0.18557202789554814  # lepton_r
# td: -0.17077545867623511  # lepton_l imu0
# td: -0.164752   # lepton_l imu0 vins estimated
# td: -0.1833045841356166  # lepton_l imu1
# td: -0.1831414182891985
# td: -0.014681057646229663  # lepton57 imu0
td: -0.012138  # vins estimated

# td: -0.057468  # cir imu0 vins estimate calib bag
# td: -0.056936  # cir imu1 vins estimate calib bag

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "~/output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
